### ISSUE TITLE
[containerd 原理剖析与实战 - 4.3 crictl 的使用 ] P146-创建pod案例失败

### ISSUE THREAD

**Issue by dingtianwei** [zhaojizhuang/containerd-book#1]
老师你好，我最近正在拜读《containerd 原理剖析与实战》这本书，收益颇多，感谢！
在实践4.3 crictl 的使用这一章P146页的第一个案例创建pod时报错，
## 环境如下
OS: Ubuntu 20.04.6 LTS
Containerd version: 1.6.31
crictl version : v1.26.0

containerd 配置，按照kubernetes官网的指导和国内环境，相对于`containerd config default`默认配置，修改如下
```bash
$ diff /etc/containerd/config.toml /etc/containerd/config.toml.default
63c63
<     sandbox_image = "registry.aliyuncs.com/google_containers/pause:3.5"
---
>     sandbox_image = "registry.k8s.io/pause:3.6"
127c127
<             SystemdCgroup = true
---
>             SystemdCgroup = false
255d254
<
```

## 操作和报错如下
书中代码和命令如下
```yaml
# pod-config.json
{
  "metadata": {
    "name": "busybox-sandbox",
    "namespace": "default",
    "attempt": 1
  },
  "log_directory": "/tmp",
  "linux": {
  }
}
```
使用`crictl runp pod-config.json` 启动pod sandbox，报错如下
```
E0508 15:09:39.374465  549376 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format \"slice:prefix:name\" for systemd cgroups, got \"/k8s.io/eba39511a4b1cbb08fad02d6b7765fdfbd6262695b46edee933da69f871f8f64\" instead: unknown"
FATA[0000] run pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/eba39511a4b1cbb08fad02d6b7765fdfbd6262695b46edee933da69f871f8f64" instead: unknown
```

个人已经排查两三天，依然没有头绪，请问是我哪里配置错误了嘛？

**Comment by zhaojizhuang** [comment]
@dingtianwei  可以改回 SystemdCgroup = false 试试

**Comment by dingtianwei** [comment]
@zhaojizhuang 感谢答复，修改 `SystemdCgroup = false`  可以创建pod。这里还有一些困惑请教：

0. 这个节点是计划要加入到集群中，所以配置项是按照加入集群的要求配置的。
1. Kubernetes官网中，是需要修改containerd的配置项`SystemdCgroup = true` 。
2. 根据我有限的理解（我还在试图去学习和理解服务、进程 和 cgroup配置的关系），kubelet和 crictl 都是调用containerd的cri插件，为什么`kubelet`调用cri需要`SystemdCgroup = true` ，但是`crictl`却出现Error？


我个人猜想的原因是: `kubelet`是使用`systemd`，与`cri`配置是一致；而 `crictl`是使用`cgroupfs`且不能指定使用`systemd`，与`cri`配置不一致。不知道是不是这样，或许只是我胡乱猜测，就像之前提到的，事实上我还在努力尝试用去学习和理解服务、进程 和 `cgroup`配置的关系。

回到问题，为什么 `kubelet`  可以  `SystemdCgroup = true` ；但 `crictl` 不能使用这个配置？

**Comment by zhaojizhuang** [comment]
@dingtianwei 猜测你是先 安装的 kubelet 和 containerd，使用的 cgroup，之后又将 containerd 的配置改为了 systemd。不知道是否是这样，如果是的话，可以在初始化集群安装的时候，二者均设为 systemd。

**Comment by dingtianwei** [comment]
@zhaojizhuang  全新系统，只安装了crictl 和 containerd， 并且将containerd进行了最初的配置，并没有安装kubelet等

**Comment by dingtianwei** [comment]
@zhaojizhuang 就像您提到的那样，kubelet需要配置`SystemdCgroup = true`，而crictl 则需要配置 `SystemdCgroup = false`才可以创建pod。
它们都是使用cri，为什么cri插件的配置要不同？

**Comment by zhaojizhuang** [comment]
kubelet 和 crictl 调用是没区别的，都是通过 CRI 接口，看下 crictl，containerd，以及 cgroup 的版本。

**Comment by dingtianwei** [comment]
@zhaojizhuang 
Containerd version: 1.6.31
crictl version : v1.26.0
cgroup version: v1

```bash
$ stat -fc %T /sys/fs/cgroup/
tmpfs
$ crictl --version
crictl version v1.26.0
$ containerd --version
containerd containerd.io 1.6.31 e377cd56a71523140ca6ae87e30244719194a521

```

**Comment by dingtianwei** [comment]
@zhaojizhuang  上午好
我使用的环境在这里：https://github.com/dingtianwei/vagrant-crictl-case/tree/main
辛苦老师有时间的时候可以帮忙看一下

**Comment by dingtianwei** [comment]
@zhaojizhuang  
 老师你好，我前几天补充学习了一下cgroups相关的东西，目前这个Issue已经基本解决，解决方法为在 `pod-config.json` 中配置`linux.cgrou_parent` ，最终json文件如下：
```json
{
  "metadata": {
    "name": "busybox-sandbox1",
    "namespace": "default",
    "attempt": 1,
    "uid": "fhcid83djaidwnduwk28bcsb"

  },
  "log_directory": "/tmp",
  "linux": {
    "cgroup_parent": "/kubepods.slice/kubepods-besteffort.slice"
  }
}
```
使用这个配置，可以使用`crictl runp` 创建pod。

这个问题的排查，顺便也解决我的另外一个困惑：既然cri中已经配置了`cgroupDriver`， 为什么`kubelet` 还需要配置？

个人总结的原因是这样（不严格，细节或某些描述不一定正确，只是整体上便于我理解）：

1. 使用`systemd`配置和管理的`cgoups`层级为`slice:prefix:name`。可用通过`systemd-cgls` 查看系统的`cgroup`直观观察。
2. 对于containerd 来说，它只负责通用的`cgoups`部分，不管是采用`cgroupfs` 还是采用`systemd` ，都是一样的。
4. 如果containerd中配置`systemdGroup=true`，containerd的通用的`cgroup`部分不能直接使用，还需要借助cri客户端告诉它更多的信息以符合`systemd cgroups`的配置标准。
5. crictl使用中的json文件的`linux.cgroup_parent` 字段，正是这个作用，用来指定cri配置容器时使用什么`slice`


排查过程如下：

1、报错中有个信息` expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/eba39511a4b1cbb08fad02d6b7765fdfbd6262695b46edee933da69f871f8f64" instead` ，表示得到的错误的`cgroups`格式；
2、开启containerd的debug日志，对比crictl和kubelet创建pod时的日志，发现kubelet创建时，日志中有个关键信息的区别，如下
```
-----crictl-----

Linux:&LinuxPodSandboxConfig{CgroupParent:,SecurityContext:nil,Sysctls:map[string]string{},Overhead:nil,Resources:nil,},
Windows:nil,}"

------kubelet----

Linux:&LinuxPodSandboxConfig{CgroupParent:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pode06e8683_23bf_440c_99bf_29385d4e9958.slice,
SecurityContext:&LinuxSandboxSecurityContext{NamespaceOptions:&NamespaceOption{Network:POD,Pid:CONTAINER,Ipc:POD,TargetId:,UsernsOptions:nil,},SelinuxOptions:nil,RunAsUser:nil,ReadonlyRootfs:false,SupplementalGroups:[],Privileged:false,SeccompProfilePath:runtime/default,RunAsGroup:nil,Seccomp:&SecurityProfile{ProfileType:RuntimeDefault,LocalhostRef:,},Apparmor:nil,},Sysctls:map[string]string{},Overhead:nil,Resources:nil,}
```
3、参考cri-tools的源码对该项进行配置
4、按照新的配置，成功创建pod

虽然这个问题解决了，但我对这个问题的理解还有很多不准确或者错误的地方，如果老师有时间的话可以帮忙指出来。

感谢老师的回答和帮助。
